name: Auto Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**' # Не запускать, если изменилась только папка dist
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код
        uses: actions/checkout@v3
      - name: Устанавливаем Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Устанавливаем зависимости
        run: npm install
      - name: Собираем проект
        run: npm run build
      - name: Сохраняем новые файлы
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Робот: автоматическая сборка [skip ci]"
          file_pattern: 'dist/*'
